[package]
name = "scratch_vm"
version = "0.1.0"
authors = ["Makoto"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2",  features = ["serde-serialize"] }
zip = { version = "0.5", default-features = false, features = ["deflate"] }
error-chain = "0.12"
console_error_panic_hook = "0.1"
js-sys = "0.3"
yew = "0.17"
log = "0.4"
wasm-logger = "0.2"
wasm-bindgen-futures = "0.4"
async-trait = "0.1"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Element",
    "HtmlElement",
    "Node",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "File",
    "HtmlImageElement",
    "Blob",
    "BlobPropertyBag",
    "Url",
    "TextMetrics",
]
