[package]
name = "scratch_vm"
version = "0.1.0"
authors = ["Makoto"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
zip = { version = "0.5", default-features = false, features = ["deflate"] }
bytes = "0.5"
