[package]
name = "scratch_vm"
version = "0.1.0"
authors = ["Makoto"]
edition = "2018"
license  = "GPL-3.0-or-later"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
zip = { version = "0.5", default-features = false, features = ["deflate"] }
error-chain = "0.12"
console_error_panic_hook = "0.1"
js-sys = "0.3"
yew = "0.17"
log = "0.4"
wasm-logger = "0.2"
wasm-bindgen-futures = "0.4"
async-trait = "0.1"
gloo-timers = { version = "0.2", features = ["futures"] }
palette = "0.5"
lazy_static = "1.4"
tokio =  { version = "1.0", features = ["sync", "rt-multi-thread", "macros"] }
yew-router = "0.14"
futures = "0.3"
hex = "0.4"
rand = { version = "0.8", features = ["small_rng"] }
getrandom = { version = "0.2", features = ["js"] }
debug-macro = "0.1.0"
strum = { version = "0.20", features = ["derive"] }
ndarray = "0.14"
conrod_core = "0.71"
piston2d-graphics = "0.37"
conrod_piston = "0.71"
piston_window = "0.113"
flo_curves = "0.4"
usvg = "0.13"
tiny-skia = "0.3"
resvg = "0.13"
image = "0.23"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Element",
    "HtmlElement",
    "Node",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "File",
    "HtmlImageElement",
    "Blob",
    "BlobPropertyBag",
    "Url",
    "TextMetrics",
    "Path2d",
    "Performance",
    "DomRect",
    "DomRectReadOnly",
    "EventTarget",
    "ImageData",
]
