[package]
name = "scratch_vm"
version = "0.1.0"
authors = ["Makoto"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2",  features = ["serde-serialize"] }
zip = { version = "0.5", default-features = false, features = ["deflate"] }
bytes = "0.5"
petgraph = { version = "0.5", default-features = false }
error-chain = "0.12"
console_error_panic_hook = "0.1"
js-sys = { version = "0.3", features = [] }

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "Node",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
]
